name: ${name}
main: ${main}
version: ${version}
author: ${author}
api-version: '1.21'
load: POSTWORLD
description: Automatically resets a world at a configurable interval.
depend:
  - Multiverse-Core
softdepend:
  - PlaceholderAPI
